apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
  labels:
    example: basic
spec:
  dex:
    openShiftOAuth: true
  namespace: argocd
  labels:
    example: basic
  server:
    route:
      enabled: true
