apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysample-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test-app-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app_dev
    repoURL: https://github.com/jtarte/sample_argocd
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: test-app-dev
        server: https://kubernetes.default.svc
      source:
        path: app_dev
        repoURL: https://github.com/jtarte/sample_argocd
        targetRevision: master